- name: Install AWX with dependencies
  hosts: all
  become: yes
  vars:
    awx_namespace: awx
    project_directory: /var/lib/awx/projects
    storage_size: 2Gi
    awx_install_dir: ./awx_install
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache is valid for 1 hour

    - name: Install Python3 and Pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install k3s using official script
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | sh -
        creates: /usr/local/bin/k3s

    - name: Install Kustomize
      ansible.builtin.shell:
        cmd: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        chdir: /usr/local/bin
        creates: /usr/local/bin/kustomize

    - name: Move Kustomize to the /usr/local/bin directory
      ansible.builtin.shell:
        cmd: mv kustomize /usr/local/bin
        creates: /usr/local/bin/kustomize

    - name: Fetch latest AWX Operator release tag
      ansible.builtin.shell:
        cmd: curl -s https://api.github.com/repos/ansible/awx-operator/releases/latest | grep tag_name | cut -d '"' -f 4
      register: release_tag
      changed_when: false

    - name: Create AWX namespace if not exists
      ansible.builtin.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ awx_namespace }}"
        state: present

    - name: Ensure AWX installation directory exists
      ansible.builtin.file:
        path: "{{ awx_install_dir }}"
        state: directory
        mode: '0755'

    - name: Generate AWX deployment configuration
      ansible.builtin.copy:
        dest: "{{ awx_install_dir }}/awx.yaml"
        content: |
          ---
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: awx
          spec:
            service_type: nodeport
            nodeport_port: 30060
            projects_persistence: true
            projects_existing_claim: awx-projects-claim

    - name: Generate Persistent Volume (PV) and Persistent Volume Claim (PVC)
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ awx_install_dir }}/{{ item.dest }}"
      loop:
        - { src: 'pv_template.yml', dest: 'pv.yml' }
        - { src: 'pvc_template.yml', dest: 'pvc.yml' }

    - name: Setup Kustomize configuration
      ansible.builtin.template:
        src: "kustomization_template.yaml"
        dest: "{{ awx_install_dir }}/kustomization.yaml"

    - name: Deploy AWX using Kustomize
      ansible.builtin.shell:
        cmd: kustomize build "{{ awx_install_dir }}" | kubectl apply -f -
        chdir: "{{ awx_install_dir }}"
      register: kustomize_output
      failed_when: kustomize_output.stderr != ""
