- name: Install AWX with dependencies
  hosts: all
  become: yes
  vars:
    awx_namespace: awx
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache is valid for 1 hour

    - name: Ensure Python3 and Pip are installed
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install the Kubernetes Python library
      ansible.builtin.pip:
        name: kubernetes
        executable: pip3

    - name: Download and install Kustomize
      ansible.builtin.shell:
        cmd: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        creates: /usr/local/bin/kustomize
      args:
        chdir: /usr/local/bin

    - name: Install community.kubernetes collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.kubernetes
      changed_when: false

    - name: Create a namespace in Kubernetes
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ awx_namespace }}"

    - name: Generate AWX resource file
      ansible.builtin.copy:
        dest: "./awx.yaml"
        content: |
          ---
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: awx
          spec:
            service_type: nodeport
            nodeport_port: 30060

    - name: Fetch latest release tag of AWX Operator
      ansible.builtin.uri:
        url: "https://api.github.com/repos/ansible/awx-operator/releases/latest"
        return_content: yes
      register: github_release
      changed_when: false

    - name: Set release tag variable
      ansible.builtin.set_fact:
        release_tag: "{{ github_release.json['tag_name'] }}"

    - name: Create kustomization.yaml
      ansible.builtin.copy:
        dest: "./kustomization.yaml"
        content: |
          ---
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - 'github.com/ansible/awx-operator/config/default?ref={{ release_tag }}'
            - awx.yaml
          images:
            - name: quay.io/ansible/awx-operator
              newTag: {{ release_tag }}
          namespace: {{ awx_namespace }}

    - name: Apply Kustomize configuration
      ansible.builtin.command:
        cmd: kustomize build . | kubectl apply -f -
