---
- name: Install AWX with dependencies
  hosts: all
  become: yes
  vars:
    awx_namespace: awx
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # This ensures the cache is valid for 1 hour; adjust as needed

    - name: Ensure Python3 and Pip are installed
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install the Kubernetes Python library
      pip:
        name: kubernetes
        executable: pip3

    - name: Download and install Kustomize
      ansible.builtin.shell:
        cmd: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        executable: /bin/bash
      args:
        chdir: /usr/local/bin
        creates: /usr/local/bin/kustomize
      notify:
        - Run install Kustomize script

    - name: Ensure namespace exists
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ awx_namespace }}"
      register: namespace_result

    - name: Display creation result
      ansible.builtin.debug:
        msg: "Namespace created: {{ namespace_result }}"

    - name: Generate AWX resource file
      copy:
        dest: "./awx.yaml"
        content: |
          ---
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: awx
          spec:
            service_type: nodeport
            nodeport_port: 30060

    - name: Fetch latest release tag of AWX Operator
      uri:
        url: "https://api.github.com/repos/ansible/awx-operator/releases/latest"
        return_content: yes
      register: github_release
      changed_when: false

    - name: Set release tag variable
      set_fact:
        release_tag: "{{ github_release.json['tag_name'] }}"

    - name: Create kustomization.yaml
      copy:
        dest: "./kustomization.yaml"
        content: |
          ---
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - 'github.com/ansible/awx-operator/config/default?ref={{ release_tag }}'
            - awx.yaml
          images:
            - name: quay.io/ansible/awx-operator
              newTag: {{ release_tag }}
          namespace: {{ awx_namespace }}

    - name: Apply Kustomize configuration
      command: kustomize build . | kubectl apply -f -

  handlers:
    - name: Run install Kustomize script
      command: "/usr/local/bin/kustomize"
      args:
        creates: "/usr/local/bin/kustomize"
